stages:
  - build
  - test
services:
  - name: mariadb
    alias: mysql


build:
  image: docker
  stage: build
  script:
     - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
     - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}" .
     - docker push "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}"

test:
  image: "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}"
  script:
     - cd /opt/app
     - export DATABASE_TYPE=mysql DATABASE_DSN="mysql:host=mysql;dbname=$MYSQL_DATABASE"
     - export DATABASE_USER=root DATABASE_PASSWORD=$MYSQL_ROOT_PASSWORD
     - bash scripts/setup.sh install_only
     - cat propel.xml
     - vendor/bin/propel config:convert
     - vendor/bin/propel sql:build
     - vendor/bin/propel sql:insert
     - vendor/bin/phpunit

variables:
  MYSQL_DATABASE: cedric
  MYSQL_ROOT_PASSWORD: coin
