language: ruby
services:
- docker
script:
- docker build -t ndamiens/nginx-php .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  global:
  - secure: D6uRztgIyTDd7aCI5tiqt4JPH9vOZPJi9UZvlQtQiLnHipgYuylB3kPSnnEnC1OgJ+IBYav3p4eggsUTcm2boiAmUfjb0q0M8e3L6cNhZj8ZT+C/mLVJZO5IuUi9j+J9fmF7loB4+gMkrPKzlvwls/piY0mFU9QHwFe68DMT00sNXuJGnXg0drj5fMJndFGm8zJ+VyKtn+3G3lqB3L1tdX/Y60f3lGABTkYa24w1xIEer3uuolbqEk9zJtJ+WcMRQ85qa6XYiblWnhRBQ4l7n3uvqWd86wWVZr0uhvqPFnjQbjU9sboYZSNM4ZTsDxBk8xF4qXU+42HzN2M7I16kZTuW3ud7FKcu32YkF5jURM1fZI6JiOkTAO9xQ5kflizpzSYDj8ZZpOFJHta3CfpBHH8gXz5SoWkCA9ekPC1XtspuVHNaXuaAxAB6fyviYs/8xwN3tYRVAHGnJsRRNiQdgRcVxDxy7mi6FfC6mB4qMXH1weL50JuZJTzdj4+SxusfxnIo47kZJyFx0c4VFTpsCyjvuoXH+Lvua1tg+W9eW1lgaJ6g9RDO7Opsx2J67/WhU61974IjsXfz/nnyfUVRIiFiZlgR+fmk7dZ8KF3Rqj3TQwKr75yKpx5hFx/0pWb8E3MLlTZ0/tRLsW37GQqij2Ir1qP8xiozqouC8zcVPxY=
  - secure: WLYhPScGQPsOwp7hkwNCIhHt/8Vr8MfBW/s9S3GIDnMY0NTUu1OHM/zE9EbRaP8trmKClKF/FqZ8hx6bXVH/9A1iDkjKnaZgmLlUzc/JNwM9sZdmzcv9kYwHko4FZF+M5BbTIF0TsFk1z0Ggye3bfPepynqLbXt01hezV1vWHnENdAM3Cuqm/2ZlqvM2o0NrCrXDeRrknnMHeyyfI8BGhtQGbAMfJX6C1/Rn2FRW5DB4lZt6ycr1RGrRUAUfmp2/BuXuvCfXyq55pB1NB4JB/GL2XpEnKK4UT8IMzPHnBYuqMTkCvDWzKC0bLOgHsS1wdNmz4bgZsg6Q5qqkKRsk7s7VIATX0T+EGYQvmrEW8iIfjTCbE89j/spKzGoWFz3cNHxuTdm2CEOKSUnCM/Xdnp8eO0q9ujOzobayL28M5MFCeehG55M8sCE/wvTdJeEYhqLATpmtK1KBlYc5Fgsh/29RCH9pDq3jAV9rjRlZ3eXrAlo58n7nZb8/43o+rDUJnRhja/QtsFaOghTmo9csWDuxrVTXmWVk+lq0zcx6XFX9CBDDWLxrpr5pkt6uwk+qzOnq1xYL/qt74oUmtpynaG2ERc5YXIlhcedsK8qShwTobcs7moLo6L1ebcqV2mkR7AStbfy+8FIM0rZakcVPDn3N2z5eCxwXcN73hvVTMV4=
